let num1 = 20, nume=3;

try {
    let resultado = num1/num2;
    console.log("La divis칩n es: " + resultado);
    throw "Ha ocurrido un error";
} catch (error) {
    console.log(error);
}

/*RESUMEN:

throw: Sirve para crear un error, el cual le ser치 pasado
como par치metro a catch. Es posible crear un error de diferentes
tipos de datos: Objeto, String, Array...

finally: Es capaz de tener m치s "peso" que el mismo Try.

*/